Repository hakadoriya/github-actions-github-apps-token, pull requests merged in 2024-08, with the labels that each got.

#1 feat: Init
  .bin/github-apps-token
  .github/CODEOWNERS
  .github/dependabot.yml
  .github/pull_request_template.md
  .github/release.yml
  .github/workflows/auto-assign.yml
  .github/workflows/label-checker.yml
  .github/workflows/task-list-checker.yml
  .github/workflows/typo-checker.yml
  LICENSE
  README.md
  action.yml
Labels: feat

#2 docs: Update README.md
  README.md
Labels: docs

#3 fix: Modify to use Client ID
  .bin/github-apps-token
  README.md
  action.yml
Labels: fix

#4 refactor: Fix action.yml for generate-apps-token script
  .bin/github-apps-token
  action.yml
Labels: refactor

#5 fix: Output error if failed to call API
  action.yml
Labels: fix

#6 ci: Modify default jwt-expiry-seconds 300 to 600
  README.md
  action.yml
Labels: fix
